apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - env:
        image: kiro123/my-nginx-webserver:0.0.0
        imagePullPolicy: Always
        name: blog
        ports:
        - containerPort: 80